### PR TITLE
install latest hotfixes.

### PR DESCRIPTION
**Pull request by jone**
- Fix errors in hotfixes update script in order to get not-yet-fixed hotfixes
- Add [Products.PloneHotfix20161129](https://plone.org/security/hotfix/20161129)
- Add [Products.PloneHotfix20170117](https://plone.org/security/hotfix/20170117)

### CODE REVIEW

**Comment by lukasgraf** [comment]
@jone https://plone.org/security/hotfix/20161129

> **Required Manual Steps**
>
> If you have enabled commenting on your Plone site, you will also need to apply an additional manual step.
> [ ...] `/@@apply-hotfix20161129`

So is `plone.app.discussion` being used anywhere in our projects?

**Comment by jone** [comment]
Yes, but rarely.
We could do a usage stats analysis (look for `Discussion Item`).

**Comment by maethu** [comment]
ftw.blog i using plone.app.discussions. It may also be enabled in custom policies.

**Comment by maethu** [comment]
Detailed analysis is here:
- https://github.com/4teamwork/opengever.core/issues/2550
- https://github.com/4teamwork/opengever.core/issues/2554


Generally in OnegovBox I don't see any issues applying those two patches.

**Comment by buchi** [comment]
👍 can be merged.

**Pull request merged**
