### PR TITLE
Precompile locals files bofore starting instance0

### PR DESCRIPTION
**Pull request by Nachtalb**

### CODE REVIEW

**Comment by maethu** [comment]
I was just about to say the same as @lukasgraf 
We had this issue already and solved it by separate config... but this lead to other issues. 
@Nachtalb Where you got this issues and why is it necessary?

**Comment by Nachtalb** [comment]
@maethu when @lukasgraf helped me finding an error in something and we started the instance 0 he saw this and we said I should ask @jone what we should do about this in the `production-v2.cfg` configuration. After that, I asked @jone if it should be extended or do something else and he told me to add it exactly like this commit.

> This does not precompile these files before starting instance0. It compiles them during buildout time

Sorry for the misunderstanding, I will update the commit message accordingly. Or if you want I will wait until this discussion is resolved.

**Comment by lukasgraf** [comment]
We addressed this in GEVER by simply including the already existing `precompile.cfg` in a separate `standard-deployment-v2.cfg`:
https://github.com/4teamwork/gever-buildouts/blob/master/standard-deployment-v2.cfg

We know for a fact that these deployments use a recent `setuptools` version, and with the precompilation done via a separate cfg, we have all the flexibility we need to include it where it's needed, and omit it where it causes problems.

I currently don't quite see the motivation for changing this and getting rid of this flexibility, as it's trivial enough to include.

**Comment by jone** [comment]
We've decided that we do not want that.
- The `precompile.cfg` can be extended for now, for the same effect.
- The `precompile.cfg` and this change can cause problems, that's why we do not want it be default for now.
- We want a pluggable system where we can just remove the extends when we run into trouble.
- We will have to solve the problem at some point by finding a new approach. This is not top priority at the moment.

**Pull request closed without merging**
