### PR TITLE
Default to doing shallow clones with mr.developer

### PR DESCRIPTION
**Pull request by Rotonen**
Ported over from https://github.com/4teamwork/opengever.core/pull/5238/files/b41eab4636f785e3cc28fb31e513c6b2f8ee8ea2#diff-33a01409c3ba8a0f72240989bb6def9b

### CODE REVIEW

**Comment by jone** [comment]
This breaks various builds which checkout a non-`master`-branch.
The [git docu says](https://git-scm.com/docs/git-clone#git-clone---depthltdepthgt) `Implies --single-branch  [...].`.
I assume that mr.developer first checks out the HEAD-branch and then changes the branch.

Also: I'm missing the WHY in the pull request description. The PR description should always contain the reason why this change is made, even when it is obvious 😉

**Comment by Rotonen** [comment]
The depth here is fetch depth. You are correct it fetches HEAD + N, and then tries to do a hard reset to a refspec. If the target branch HEAD is not within N of the default branch HEAD. This should only be an issue if we're depending on some stale branch of an otherwise active project.

So, do we bump the depth or do we drop this optimisation?

**Comment by lukasgraf** [comment]
I say drop it. I was under the assumption it should be free of side-effects, which it wasn't. Would have been nice to upstream it and not just do it for GEVER, but I don't think it's something we should invest any time in for the time being. => revert.

**Comment by jone** [comment]
I agree 👍 
`mr.developer` would have to clone with the `--branch` option and not switch branch after cloning.

**Comment by Rotonen** [comment]
That could hit issues with Github as they do not allow one to fetch unadvertised objects for performance reasons - thus the strategy most things (like Travis) adopt - fetch default branch HEAD with a depth of 10 .. 100 and hard reset to refspec.

**Comment by Rotonen** [comment]
Until you need any other state of that branch than the current HEAD of it.

**Pull request merged**
