### PR TITLE
Add bumblebee.cfg

### PR DESCRIPTION
**Pull request by elioschmutz**
Config-File to add ftw.bumblebee with the taskqueue configuration.

### CODE REVIEW

**Comment by deiferni** [comment]
We need this configuration for productive deployments as well, i think you should configure both the `[instance]` (dev) and `[instance0]` (prod) sections.

- I'd suggest to add `ftw.bumblebee` to `instance-eggs`
- Create a [bumblebee] section that contains the necessary configuration (`zope-conf-additional`) and include it for both instances

Inspiration: https://github.com/4teamwork/ftw-buildouts/blob/master/raven.cfg

**Comment by elioschmutz** [comment]
@deiferni :+1:

**Comment by elioschmutz** [comment]
Tests are failing, but I don't know why... someone have an idea?

@deiferni @jone

**Comment by deiferni** [comment]
I think this package should not be tested, the test-configs are here to be extended from. i deactivated this package for further ci builds.

**Comment by elioschmutz** [comment]
:+1: ok, thanks!

**Pull request merged**
